/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development and committed here so
// the foundation typecheck works in a clean repo.
