/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hooks/claude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a Claude Code hook event */
        post: operations["ingestClaudeHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List flows */
        get: operations["listFlows"];
        put?: never;
        /** Create flow */
        post: operations["createFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{flowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get flow */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{flowId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger flow run */
        post: operations["runFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs */
        get: operations["listRuns"];
        put?: never;
        /** Create a Run */
        post: operations["createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run DAG */
        get: operations["getRunDag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a checkpoint produced by the runner */
        post: operations["createCheckpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE stream of run events */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get node detail */
        get: operations["getNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/nodes/{nodeId}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override node policy */
        post: operations["overrideNodePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay a run from a node */
        post: operations["replayRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}/replay/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get replay recommendation */
        get: operations["getReplayRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runners */
        get: operations["listRunners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runners/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runner heartbeat */
        post: operations["runnerHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Flow: {
            id: string;
            name: string;
            description?: string | null;
            repo_path: string;
            agent: string;
            active_version_id: string;
            schedule?: string | null;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FlowCreate: {
            name: string;
            description?: string;
            repo_path: string;
            prompt: string;
            schedule?: string;
            /** @enum {string} */
            replay_mode?: "manual" | "semi_automatic" | "automatic";
            /** @enum {string} */
            side_effect_policy?: "label_only" | "require_approval" | "block_dangerous";
        };
        Run: {
            id: string;
            flow_id?: string | null;
            flow_version_id?: string | null;
            runner_id?: string | null;
            /** @enum {string} */
            run_kind: "ad_hoc" | "registered_flow" | "scheduled";
            /** @enum {string} */
            status: "queued" | "running" | "failed" | "success" | "cancelled";
            original_prompt: string;
            repo_path: string;
            workspace_path?: string | null;
            root_branch_id: string;
            current_branch_id: string;
            failure_node_id?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RunCreate: {
            id: string;
            flow_id?: string | null;
            flow_version_id?: string | null;
            runner_id?: string | null;
            run_kind: string;
            status: string;
            original_prompt: string;
            repo_path: string;
            workspace_path?: string | null;
            root_branch_id: string;
            current_branch_id: string;
        };
        RunDag: {
            run: components["schemas"]["Run"];
            nodes: components["schemas"]["NodeSummary"][];
            edges: components["schemas"]["Edge"][];
            checkpoints: components["schemas"]["Checkpoint"][];
            groups: components["schemas"]["RunGroup"][];
            side_effects?: components["schemas"]["SideEffectLog"][];
        };
        NodeSummary: {
            id: string;
            run_id: string;
            branch_id: string;
            group_id?: string | null;
            type: string;
            label: string;
            tool_name?: string | null;
            status: string;
            recovery_policy: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            duration_ms?: number | null;
            output_preview?: string | null;
            error?: string | null;
        };
        NodeDetail: components["schemas"]["NodeSummary"] & {
            input_json?: Record<string, never> | null;
            output_json?: Record<string, never> | null;
            classification_reason?: string | null;
            classification_confidence?: number | null;
            checkpoint_before_id?: string | null;
            checkpoint_after_id?: string | null;
            artifacts?: components["schemas"]["Artifact"][];
        };
        Edge: {
            id: string;
            run_id: string;
            branch_id: string;
            source_node_id: string;
            target_node_id: string;
            edge_type: string;
        };
        Checkpoint: {
            id: string;
            run_id: string;
            branch_id: string;
            node_id?: string | null;
            label: string;
            backend: string;
            git_ref?: string | null;
            git_commit_hash?: string | null;
            workspace_path: string;
            diff_summary?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CheckpointCreate: {
            label: string;
            backend: string;
            git_ref: string;
            git_commit_hash: string;
            workspace_path: string;
            branch_id: string;
            node_id?: string | null;
            diff_summary?: string | null;
            file_hashes_json?: Record<string, never> | null;
        };
        RunGroup: {
            id: string;
            run_id: string;
            parent_group_id?: string | null;
            label: string;
            kind: string;
            status: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
        };
        Artifact: {
            id: string;
            run_id: string;
            node_id?: string | null;
            produced_by_node_id?: string | null;
            type: string;
            path?: string | null;
            source_url?: string | null;
            description?: string | null;
            content_preview?: string | null;
            content_hash?: string | null;
            size_bytes?: number | null;
            /** Format: date-time */
            created_at: string;
        };
        SideEffectLog: {
            id: number;
            run_id: string;
            branch_id: string;
            node_id: string;
            kind: string;
            idempotency_key: string;
            external_ref?: string | null;
            status: string;
            payload_preview?: string | null;
            /** Format: date-time */
            executed_at?: string | null;
        };
        ReplayRequest: {
            node_id: string;
            user_context?: string;
            edited_resume_prompt?: string;
        };
        ReplayAttempt: {
            id: string;
            run_id: string;
            source_node_id: string;
            source_checkpoint_id: string;
            parent_branch_id: string;
            new_branch_id: string;
            resume_prompt?: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
        };
        ReplayRecommendation: {
            source_node_id: string;
            recommended_checkpoint_id: string;
            confidence: number;
            reason: string[];
            reuse_node_ids: string[];
            rerun_node_ids: string[];
            approval_node_ids: string[];
            unsafe_node_ids: string[];
            generated_resume_prompt: string;
        };
        Runner: {
            id: string;
            name: string;
            machine_id?: string | null;
            status: string;
            /** Format: date-time */
            last_heartbeat_at?: string | null;
            current_run_id?: string | null;
            claude_code_available: boolean;
            version: string;
            /** Format: date-time */
            created_at: string;
        };
        RunnerHeartbeat: {
            runner_id: string;
            status: string;
            current_run_id?: string | null;
            version: string;
            claude_code_available: boolean;
        };
        PolicyOverride: {
            recovery_policy: string;
            reason?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingestClaudeHook: {
        parameters: {
            query?: never;
            header: {
                "x-runback-run-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Event accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Malformed payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flow"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Run already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRunDag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDag"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCheckpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkpoint"];
                };
            };
            /** @description Unknown run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streaming response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    overrideNodePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
                nodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyOverride"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replayRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description Replay started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayAttempt"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReplayRecommendation: {
        parameters: {
            query: {
                node_id: string;
            };
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRecommendation"];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRunners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runner"][];
                };
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runnerHeartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunnerHeartbeat"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
